# Generated by Django 3.1.1 on 2020-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('image', models.ImageField(blank=True, default='posts/default/default_post_image.jpy', upload_to='posts/img')),
                ('file', models.FileField(blank=True, upload_to='posts/file')),
                ('link', models.URLField(null=True, verbose_name='참조링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트시간')),
                ('post_type', models.PositiveSmallIntegerField(choices=[(0, '해킹'), (1, '개발'), (2, '보안'), (3, '책')], verbose_name='게시글타입')),
            ],
        ),
    ]
